/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DataMahasiswa;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import Models.ModelProdi;

/**
 *
 * @author HP
 */
public class DataProdi extends javax.swing.JFrame {
    
    static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
        static final String DB_URL = "jdbc:mysql://localhost/db_pendaftaranmhs";
        static final String USER = "root";
        static final String PASS = "";
        
        List<ModelProdi> items = new ArrayList<>();
        static Connection conn;
        static Statement stmt;
        static ResultSet rs;

    /**
     * Creates new form DataProdi
     */
    public DataProdi() {
        initComponents();
        btnEditProdi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditProdi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdi = new javax.swing.JTable();
        btnKeluar = new javax.swing.JButton();
        fldProdi = new javax.swing.JTextField();
        fld_id_prodi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Prodi ");
        setMinimumSize(new java.awt.Dimension(967, 618));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditProdi.setText("EDIT");
        btnEditProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProdiActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PRODI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAMA PRODI :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 20));

        tblProdi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID PRODI", "NAMA PRODI"
            }
        ));
        tblProdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 921, 223));

        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));
        getContentPane().add(fldProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 120, 690, -1));
        getContentPane().add(fld_id_prodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 120, 0, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/background1.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProdiActionPerformed
        // TODO add your handling code here:
        String nama_prodi = fldProdi.getText();
        int id = Integer.parseInt(fld_id_prodi.getText());
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            
            String sql = "UPDATE prodi_mhs SET Nama_Prodi = ? WHERE ID_Prodi = ? ";
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, nama_prodi);
            ps.setInt(2, id);
            
            ps.execute();
            ps.close();
            stmt.close();
            conn.close();
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        showTableData();
    }//GEN-LAST:event_btnEditProdiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        showTableData();
    }//GEN-LAST:event_formWindowOpened

    private void tblProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdiMouseClicked
        // TODO add your handling code here:
        getData();
        btnEditProdi.setEnabled(true);
    }//GEN-LAST:event_tblProdiMouseClicked

    public void showTableData() {
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID PRODI");
            model.addColumn("NAMA PRODI");

            stmt = conn.createStatement();
            String sql = "SELECT * FROM prodi_mhs;";
            items.clear();
            rs = stmt.executeQuery(sql);
            while(rs.next()) {
                items.add(new ModelProdi(rs.getInt("ID_Prodi"),rs.getString("Nama_Prodi")));
            }
            int i = 1;
            for (ModelProdi p : items) {
                model.addRow(new Object[]{
                    i,
                    p.getNama_Prodi()
                });
                i++;
            }
            
            rs.close();
            stmt.close();
            tblProdi.setModel(model);
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    public void getData() {
        int baris = tblProdi.getSelectedRow();
        fldProdi.setText(items.get(baris).getNama_Prodi());
        fld_id_prodi.setVisible(false);
        fld_id_prodi.setText(Integer.toString(items.get(baris).getID_Prodi()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditProdi;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JTextField fldProdi;
    private javax.swing.JTextField fld_id_prodi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProdi;
    // End of variables declaration//GEN-END:variables
}
